In [2]:
import requests
import pandas as pd

In [39]:
# sentiment analysis scores

params = {
  'api_token': 'v4e5qEOulw9UJn3WZWA1lvLV9py2R4hxtOHHrK8n',
    'symbols': 'FB',
    'published_on':'2022-01-02',
    'language': 'en'
}

api_result = requests.get('https://api.stockdata.org/v1/news/all?', params)

api_response = api_result.json()

df = pd.json_normalize(api_response['data'])

df

,uuid,title,description,keywords,snippet,url,image_url,language,published_at,source,relevance_score,entities,similar
0,d2867658-88ad-45e7-89e1-17b8ce80886d,Top 10 Most Searched Tickers On Benzinga Pro I...,Many of Benzinga’s most read stories in 2021 c...,,Many of Benzinga’s most read stories in 2021 c...,https://markets.businessinsider.com/news/stock...,https://cdn.benzinga.com/files/imagecache/1024...,en,2022-01-02T22:19:00.000000Z,markets.businessinsider.com,None,"[{'symbol': 'AAPL', 'name': 'Apple Inc.', 'exc...",[]
1,61a001e1-26a3-45db-b17d-40833bb44285,CES to now end sooner than planned as Omicron ...,"""The step was taken as an additional safety me...","ces 2022, ces 2022 dates, omicron, omicron cas...",Best of ETtech delivered to your Inbox SUBSCRI...,https://economictimes.indiatimes.com/tech/tech...,"https://img.etimg.com/thumb/msid-88649775,widt...",en,2022-01-02T12:45:22.000000Z,economictimes.indiatimes.com,None,"[{'symbol': 'GOOGL.BA', 'name': 'Alphabet Inc....",[]
2,2e25598f-4c71-4584-a5b1-f659a57286cb,CES to now end sooner than planned as Omicron ...,"""The step was taken as an additional safety me...","ces 2022, ces 2022 dates, omicron, omicron cas...",Best of ETtech delivered to your Inbox SUBSCRI...,https://economictimes.indiatimes.com/tech/ette...,"https://img.etimg.com/thumb/msid-88649775,widt...",en,2022-01-02T12:45:22.000000Z,economictimes.indiatimes.com,None,"[{'symbol': 'GOOGL.BA', 'name': 'Alphabet Inc....",[]

In [36]:
api_response

{'error': {'code': 'invalid_api_endpoint',
  'message': 'The requested API endpoint is invalid.'}}

In [24]:
#df['ticker'] = df['data'][0][0]
df['ticker'] = None
df['num_doc'] = None
df['sentiment_avg'] = None
for i in range(len(df)):
    df['ticker'].loc[i] = df['data'].loc[i][0]['key']
    df['num_doc'].loc[i] = df['data'].loc[i][0]['total_documents']
    df['sentiment_avg'].loc[i] = df['data'].loc[i][0]['sentiment_avg']
df = df.drop(['data'], axis = 1)

In [25]:
df

                         date ticker num_doc sentiment_avg
0    2022-04-29T00:00:00.000Z   TSLA     112      0.291916
1    2022-04-28T00:00:00.000Z   TSLA      92      0.183581
2    2022-04-27T00:00:00.000Z   TSLA     133      0.223368
3    2022-04-26T00:00:00.000Z   TSLA     190      0.203158
4    2022-04-25T00:00:00.000Z   TSLA     144      0.321131
..                        ...    ...     ...           ...
479  2021-01-05T00:00:00.000Z   TSLA       8      0.354055
480  2021-01-04T00:00:00.000Z   TSLA      15      0.282543
481  2021-01-03T00:00:00.000Z   TSLA       9      0.350567
482  2021-01-02T00:00:00.000Z   TSLA       2      0.142859
483  2021-01-01T00:00:00.000Z   TSLA       2      0.371512

[484 rows x 4 columns]